name: Inferno CI US Core v3.1.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TEST_KIT_REPO: https://github.com/inferno-framework/us-core-test-kit.git
  TEST_KIT_NAME: us-core-test-kit
  TEST_KIT_RELEASE: v0.8.2

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout server
        uses: actions/checkout@v4

      - name: Fetch latest g10 test kit
        run: git clone $TEST_KIT_REPO $TEST_KIT_NAME --branch $TEST_KIT_RELEASE --depth 1

      # TODO: delete this when inferno execute is merged
      - name: Point test kit to experimental branch
        working-directory: ${{ github.workspace }}/${{ env.TEST_KIT_NAME }}
        run: |
          echo "gem 'inferno_core', git: 'https://github.com/inferno-framework/inferno-core.git', branch: 'main'" >> Gemfile
          rm Gemfile.lock # force re-install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ${{ github.workspace }}/${{ env.TEST_KIT_NAME }}
          bundler-cache: true

      - name: Start server
        run: |
          docker compose build
          docker compose up -d
          ${{ github.workspace }}/.github/wait-for.sh localhost:8080 -- echo "Server ready"

      - name: Start Inferno services
        working-directory: ${{ github.workspace }}/${{ env.TEST_KIT_NAME }}
        run: |
          gem install foreman
          bundle exec inferno migrate
          bundle exec inferno services start
          ${{ github.workspace }}/.github/wait-for.sh http://localhost:80/hl7validatorapi/validator/version -- echo "Inferno services ready"

      - name: Run test kit
        working-directory: ${{ github.workspace }}/${{ env.TEST_KIT_NAME }}
        run: |
          bundle exec inferno execute --suite us_core_v311 \
                                      --groups 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 2.10 2.11 2.12 2.13 2.14 2.15 2.16 2.17 2.18 2.19 2.20 2.21 2.22 2.23 2.24 2.25 2.26 2.27 2.28 2.29 2.30 2.31 2.32 \
                                      --inputs "url:localhost:8080/reference-server/r4" \
                                               patient_ids:85,355 \
                                               "smart_credentials:{\"access_token\":\"SAMPLE_TOKEN\"}"


      - name: Stop server
        run: docker compose down

      - name: Stop Inferno services
        working-directory: ${{ github.workspace }}/${{ env.TEST_KIT_NAME }}
        run: bundle exec inferno services stop
